// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfhfnwgyifjexqciktsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmaGZud2d5aWZqZXhxY2lrdHNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNTIyODksImV4cCI6MjA3MDcyODI4OX0.dL7QLAiuGamkS5_mDhcSsh8qhGe8vlZ-Eo4RW0A2Ip8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});